<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Carbon\Carbon;
class NotificationController extends Controller
{

    public function send_whatsapp(Request $request)
    {
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $url_gmap = 'google.com/maps/?q='.$request->latitude.','.$request->longitude;
        $sekarang = Carbon::parse(Carbon::now())->format('H:i:s'); 
        $data =  array(
            "from" => "14157386102",
            "to" => $request->phone,
            "message_type" => "text",
            "channel" => "whatsapp",
            "text" => Auth::user()->name." Jatuh pada pukul ".$sekarang." Klik link berikut untuk melihat lokasi di Google Map\n".$url_gmap
        );
        $ch = curl_init();
        $data_json = json_encode($data);
        curl_setopt($ch, CURLOPT_URL, 'https://messages-sandbox.nexmo.com/v1/messages');
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data_json);
        curl_setopt($ch, CURLOPT_USERPWD, '258b238d' . ':' . '0fAdjHZTmb06AVsi');

        $headers = array();
        $headers[] = 'Content-Type: application/json';
        $headers[] = 'Accept: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        return $result;
        if (curl_errno($ch)) {
            $data = [
                'success' => false,
                'message' => curl_error($ch)
            ];
        } else {
            $data = [
                'success' => true,
                'message' => 'Berhasil kirim pesan!'
            ];
        }
        curl_close($ch);
        return response()->json($data);

    }


}
